#!/usr/bin/env/bash

echo "Started backup process"
echo ""

echo "Running rebuild of home-manager and system..."
echo ""

# Run other backup things
~/scripts/rebuild-aliases/rebuild-switch
~/scripts/rebuild-aliases/home-switch

echo "Copying scripts..."
echo ""

# Copy scripts dir
cp -r ~/scripts ~/backup/scripts

echo "Committing..."
echo ""

# Commit and push changes
git -C ~/backup/ add -A > /dev/null
git -C ~/backup/ commit -m "[ $(date) ] backup"
git -C ~/backup/ push > /dev/null

echo "Finished"
